Sistema_Asomariec/urls.py
"""Sistema_Asomariec URL Configuration

The `urlpatterns` list routes URLs to view. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function view
    1. Add an import:  from my_app import view
    2. Add a URL to urlpatterns:  path('', view.home, name='home')
Class-based view
    1. Add an import:  from other_app.view import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.shortcuts import render,HttpResponse
from django.urls import path, include

def mostrar(request):
    # return render(request, 'base/body.html')
    return render(request, 'test.html')
def mostrar2(request):
    # return render(request, 'base/body.html')
    return render(request, 'base/notificaciones.html')

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('hola/prueba/', mostrar2),
    path('admin/', admin.site.urls),
    path('hola/', mostrar),
    # path('hola/prueba/', mostrar2),
    path('prueba/', mostrar2),
    path('insumo/', include('insumo.urls')),
    path('cliente/', include('cliente.urls')),
    path('proveedor/', include('proveedor.urls')),
    path('compra/', include('compra.urls')),
    path('producto/', include('producto.urls')),
    path('venta/', include('venta.urls')),
    path('login/', include('login.urls')),
    path('reports/', include('reports.urls')),
    path('user/', include('user.urls')),
    path('seguridad/', include('seguridad.urls')),
    path('empresa/', include('empresa.urls')),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

insumo/urls.py
from django.urls import path

from insumo.views import *

app_name = 'insumo'

urlpatterns = [
    # category
    path('categoria/mostrar/', CategoriaView.as_view(), name='categoria_mostrar'),
    path('categoria/create/', CategoriaCreateView.as_view(), name='categoria_create'),
    path('categoria/editar/<int:pk>/', CategoriaUpdateView.as_view(), name='categoria_update'),
    path('categoria/borrar/<int:pk>/', CategoriaDelete.as_view(), name='categoria_delete'),
    path('mostrar/', mostrar, name='insumo_list'),
    # medida
    path('medida/mostrar/', MedidaView.as_view(), name='medida_mostrar'),
    # detalle
    path('detalle/mostrar/',DetalleView.as_view(), name='detalle_mostrar'),
    # insumo
    path('insumo/mostrar/', InsumoListView.as_view(), name='insumo_mostrar'),
    path('insumo/create/', InsumoCreateView.as_view(), name='insumo_create'),
    path('insumo/editar/<int:pk>/', InsumoUpdateView.as_view(), name='insumo_edit'),
    path('insumo/eliminar/', InsumoDelete.as_view(), name='insumo_delete'),
    # path('insumo/eliminar/<int:pk>/', InsumoDeleteView.as_view(), name='insumo_delete'),

]

user/urls.py
from django.urls import path
from user.views import *

app_name = 'user'

urlpatterns = [
    # user
    path('list/', UserListView.as_view(), name='user_list'),
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    # path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('change/password/', UserChangePasswordView.as_view(), name='user_change_password'),
]

insumo/models.py
from django.db import models

from Sistema_Asomariec.models import BaseModel
from Sistema_Asomariec.settings import MEDIA_URL, STATIC_URL
# from settings import MEDIA_URL, STATIC_URL
from django.forms import model_to_dict
# Create your models here.
from datetime import datetime
from crum import get_current_user
# Create your models here.
class Categoria(BaseModel):
    catDescripcion=models.CharField(max_length=50, verbose_name='Descripcion')
    catEstado = models.BooleanField(default=True, verbose_name='Estado')
    # usuaReg = models.IntegerField(blank=True, null=True)
    # usuaMod = models.IntegerField(blank=True, null=True)
    # usuaEli = models.IntegerField(blank=True, null=True)
    # catFecReg=models.DateTimeField(auto_now_add=True, blank=True, null=True)
    # catFecMod=models.DateTimeField(auto_now=True, blank=True, null=True)
    # catFecEli=models.DateTimeField(default=datetime.now, blank=True, null=True)

    def __str__(self):
        return self.catDescripcion

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        user = get_current_user()
        if user is not None:
            if not self.pk:
                self.user_creation = user
            else:
                self.user_updated = user
        super(Categoria,self).save()

    def toJSON(self):
        item= model_to_dict(self)
        return item

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['id']


class UnidadMedidad(BaseModel):
    medDescripcion=models.CharField(max_length=50,verbose_name='Medidad')
    medEstado = models.BooleanField(default=True, verbose_name='Estado')
    # usuaReg = models.IntegerField(blank=True, null=True)
    # usuaMod = models.IntegerField(blank=True, null=True)
    # usuaEli = models.IntegerField(blank=True, null=True)
    # medFecReg = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    # medFecMod = models.DateTimeField(auto_now=True, blank=True, null=True)
    # medFecEli = models.DateTimeField(default=datetime.now, blank=True, null=True)

    def __str__(self):
        return self.medDescripcion

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        user = get_current_user()
        if user is not None:
            if not self.pk:
                self.user_creation = user
            else:
                self.user_updated = user
        super(UnidadMedidad,self).save()

    def toJSON(self):
        item= model_to_dict(self)
        return item

    class Meta:
        verbose_name = 'Medida'
        verbose_name_plural = 'Medidas'
        ordering = ['id']


class Insumo(BaseModel):
    medida=models.ForeignKey(UnidadMedidad,on_delete=models.PROTECT)
    categoria=models.ForeignKey(Categoria, on_delete=models.PROTECT)
    insCod=models.CharField(max_length=100)
    insDescripcion=models.CharField(max_length=50, verbose_name='Descripcion')
    insModelo=models.CharField(max_length=50, verbose_name='Modelo')
    insPrecio=models.DecimalField(default=0,max_digits=10,decimal_places=2)
    insIva=models.DecimalField(default=0.12,max_digits=10,decimal_places=2)
    insImagen = models.ImageField(upload_to='fotos/%Y/%m/%d', blank=True, null=True)
    insStock=models.IntegerField(default=0, blank=True, null=True,verbose_name='Stock')
    insEstado = models.BooleanField(default=True, verbose_name='Estado')
    # usuaReg = models.IntegerField(blank=True, null=True)
    # usuaMod = models.IntegerField(blank=True, null=True)
    # usuaEli = models.IntegerField(blank=True, null=True)
    # insFecReg = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    # insFecMod = models.DateTimeField(auto_now=True, blank=True, null=True)

    def __str__(self):
        return self.insDescripcion

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        user = get_current_user()
        if user is not None:
            if not self.pk:
                self.user_creation = user
            else:
                self.user_updated = user
        super(Insumo,self).save()

    def toJSON(self):
        item= model_to_dict(self)
        item['medida']=self.medida.toJSON()
        item['insImagen'] = self.get_image()
        item['instotalprecio'] = format (self.insPrecio+(self.insPrecio*self.insIva), '.2f')
        item['categoria']= self.categoria.toJSON()
        return item

    def get_image(self):
        if self.insImagen:
            return '{}{}'.format(MEDIA_URL, self.insImagen)
        return '{}{}'.format(STATIC_URL, 'img/empty.png')

    class Meta:
        verbose_name = 'Insumo'
        verbose_name_plural = 'Insumos'
        ordering = ['id']

insumo/forms.py
from django.forms import *


from insumo.models import *

class CategoriaForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # for form in self.visible_fields():
        #     form.field.widget.attrs['class'] = 'form-control'
        #     form.field.widget.attrs['autocomplete'] = 'off'
        self.fields['catDescripcion'].widget.attrs['autofocus'] = True

    class Meta:
        model= Categoria
        fields='__all__'
        # exclude=['catFecReg','catFecMod']
        widgets = {
            'catDescripcion': TextInput(
                attrs={
                    'placeholder': 'Ingrese un nombre',
                }
            ),
            # 'desc': Textarea(
            #     attrs={
            #         'placeholder': 'Ingrese un nombre',
            #         'rows': 3,
            #         'cols': 3
            #     }
            # ),
        }

        exclude=['user_creation','user_updated']

    # solo cuando voy a enviar con ajax
    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                form.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data

class MedidaForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # for form in self.visible_fields():
        #     form.field.widget.attrs['class'] = 'form-control'
        #     form.field.widget.attrs['autocomplete'] = 'off'
        self.fields['medDescripcion'].widget.attrs['autofocus'] = True

    class Meta:
        model= UnidadMedidad
        fields='__all__'
        # exclude=['catFecReg','catFecMod']
        widgets = {
            'medDescripcion': TextInput(
                attrs={
                    'placeholder': 'Ingrese un nombre',
                }
            ),
            # 'desc': Textarea(
            #     attrs={
            #         'placeholder': 'Ingrese un nombre',
            #         'rows': 3,
            #         'cols': 3
            #     }
            # ),
        }

        exclude=['user_updated','user_creation']

    # solo cuando voy a enviar con ajax
    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                form.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data

class InsumoForm(ModelForm):
    medida=ModelChoiceField(queryset=UnidadMedidad.objects.filter(medEstado=1))
    categoria=ModelChoiceField(queryset=Categoria.objects.filter(catEstado=1))
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # for form in self.visible_fields():
        #     form.field.widget.attrs['class'] = 'form-control'
        #     form.field.widget.attrs['autocomplete'] = 'off'
        self.fields['insDescripcion'].widget.attrs['autofocus'] = True

    class Meta:
        model= Insumo
        fields='__all__'
        # exclude=['catFecReg','catFecMod']
        widgets = {
            'insStock': TextInput(
                    attrs={
                        'class':'form-control',
                        'required': False,
                        'disabled':'disabled'
                        # 'placeholder': 'Ingre,
                    },


                ),
            'insPrecio': TextInput(

                attrs={
                    'class': 'form-control',
                    # 'value':'1',

                    # 'data-mask' : '00/00/0000'
                    # 'disabled': 'disabled'
                    # 'placeholder': 'Ingre',
                },


            ),
            'insIva': TextInput(

                attrs={
                    'class': 'form-control',
                    # 'value':'1',

                    # 'data-mask' : '00/00/0000'
                    # 'disabled': 'disabled'
                    # 'placeholder': 'Ingre',
                },

            ),
            'insCod': TextInput(
                attrs={
                    'class': 'form-control',
                    # 'value':'0.jh00'
                    # 'data-mask' : '00/00/0000'
                    # 'disabled': 'disabled'
                    'placeholder': 'Ingrese el Código',
                },

            ),
            'insModelo': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese el Modelo',
                },

            ),
            'insDescripcion': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese el Nombre',
                },

            ),
        }

        exclude=['user_updated','user_creation']
        #     'medDescripcion': TextInput(
        #         attrs={
        #             'placeholder': 'Ingrese un nombre',
        #         }
        #     ),
            # 'desc': Textarea(
            #     attrs={
            #         'placeholder': 'Ingrese un nombre',
            #         'rows': 3,
            #         'cols': 3
            #     }
            # ),
        # }

    # solo cuando voy a enviar con ajax
    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                # print(form.fields)
                # guarda ruta de insumo
                form.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data

templates/insumo/medida/MedidaList.html
{% extends 'base/body.html' %}
{% load widget_tweaks %}
{% load static %}
{% block head %}

    {#    <script src="{% static 'lib/plugins/jquery/jquery.min.js' %}"></script>#}
    {#    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">#}
    {#    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">#}
    {##}
    {#    <script type="text/javascript" charset="utf8"#}
    {#            src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>#}
    {#    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>#}
    <!-- Datatables -->
    <link rel="stylesheet" href="{% static 'lib/assets/vendor/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'lib/assets/vendor/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'lib/assets/vendor/datatables.net-select-bs4/css/select.bootstrap4.min.css' %}">



{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h2 class="card-title p-0">Titulo</h2>
            <div class="row">

                <div class="table-responsive py-4">
                    <table class="table table-flush" id="table_id">
                        <thead class="thead-light">
                        <tr>
                            <th>N</th>
                            <th>Nombre</th>
                            <th>Accion</th>

                        </tr>
                        </thead>
                        {#                        <tfoot>#}
                        {#                        <tr>#}
                        {#                            <th>N</th>#}
                        {#                            <th>Nombre</th>#}
                        {#                            <th>Accion</th>#}
                        {##}
                        {#                        </tr>#}
                        {#                        </tfoot>#}
                        <tbody>
                        {#                        {% for object in object_list %}#}
                        {#                            <tr>#}
                        {#                            <td>{{ object.catDescripcion }}</td>#}
                        {#                            <td>{{ object.catEstado }}</td>#}
                        {#                            </tr>#}
                        {##}
                        {#                        {% endfor %}#}

                        </tbody>
                    </table>
                </div>
            </div>
{#            <a href="{{ create_url }}" class="btn btn-primary btn-flat btnTest">#}
{#                <i class="fas fa-plus"></i> Nuevo registro#}
{#            </a>#}
            <a style="color: white" class="btn btn-primary btn-flat btnAdd">
                <i class="fas fa-plus"></i> Nuevo registro
            </a>
            <!-- Button trigger modal -->
{#            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModalCategoria">#}
{#                Launch demo modal#}
{#            </button>#}
        </div>
    </div>


{% endblock %}

{% block javascript %}



    <!-- Modal -->


    <script src="{% static 'lib/assets/vendor/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-select/js/dataTables.select.min.js' %}"></script>
    {#funcion del datatable#}
    <script src="{% static 'js/insumo/medida/list.js' %}"></script>


    <div class="modal fade" id="myModalMedida" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <form method="post" action="." enctype="multipart/form-data" id="form_ID">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Medida</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="container-fluid">
                            <input name="action" type="hidden" value="add">
                            <input name="user1" id="user1" type="hidden" value="1">
                            <input name="id" id="id" type="hidden" value="0">
                            <div class="form-group">
                                <label for="id_medDescripcion">Nombre:</label>

                                {{ form.medDescripcion|add_class:"form-control" }}
{#                                {{ form.catFecReg }}#}
{#                                {{ form.catFecMod }}#}
                            </div>
                            <div class="col-6">

                                {{ form.medEstado|attr:'checked'|attr:'type:hidden'|attr:'value:True' }}

                                {% ifequal action "add" %}
                                    {{ form.usuaReg|attr:'type:hidden'|attr:'value:1' }}
                                    {{ form.usuaMod|attr:'type:hidden' }}
                                    {{ form.usuaEli|attr:'type:hidden' }}
                                {% endifequal %}
                                {% ifequal action "edit" %}
                                    {{ form.usuaReg|attr:'type:hidden' }}
                                    {{ form.usuaMod|attr:'type:hidden'|attr:'value:1' }}
                                    {{ form.usuaEli|attr:'type:hidden' }}
                                {% endifequal %}
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                </div>
            </div>
        </form>

    </div>
{% endblock %}