Sistema_Asomariec/urls.py
"""Sistema_Asomariec URL Configuration

The `urlpatterns` list routes URLs to view. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function view
    1. Add an import:  from my_app import view
    2. Add a URL to urlpatterns:  path('', view.home, name='home')
Class-based view
    1. Add an import:  from other_app.view import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.shortcuts import render,HttpResponse
from django.urls import path, include

def mostrar(request):
    # return render(request, 'base/body.html')
    return render(request, 'test.html')
def mostrar2(request):
    # return render(request, 'base/body.html')
    return render(request, 'base/notificaciones.html')

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('hola/prueba/', mostrar2),
    path('admin/', admin.site.urls),
    path('hola/', mostrar),
    # path('hola/prueba/', mostrar2),
    path('prueba/', mostrar2),
    path('insumo/', include('insumo.urls')),
    path('cliente/', include('cliente.urls')),
    path('proveedor/', include('proveedor.urls')),
    path('compra/', include('compra.urls')),
    path('producto/', include('producto.urls')),
    path('venta/', include('venta.urls')),
    path('login/', include('login.urls')),
    path('reports/', include('reports.urls')),
    path('user/', include('user.urls')),
    path('seguridad/', include('seguridad.urls')),
    path('empresa/', include('empresa.urls')),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proveedor/urls.py
from django.urls import path

from proveedor.views import *

app_name = 'proveedor'

urlpatterns = [
    # caegory
    path('proveedor/mostrar/', ProveedorListarView.as_view(), name='proveedor_listar'),
    path('proveedor/crear/', ProveedorCrearView.as_view(), name='proveedor_crear'),
    path('proveedor/editar/<int:pk>/', ProveedorUpdateView.as_view(), name='proveedor_editar'),
    path('proveedor/eliminar/', ProveedorDelete.as_view(), name='proveedor_eliminar'),
    # path('proveedor/eliminar/<int:pk>/', ProveedorDeleteView.as_view(), name='proveedor_eliminar'),

    # path('categoria/mostrar/', CategoriaListView.as_view(), name='categoria_mostrar'),
    # path('categoria/editar/<int:pk>/', CategoriaUpdateView.as_view(), name='categoria_update'),
    # path('categoria/borrar/<int:pk>/', CategoriaDelete.as_view(), name='categoria_delete'),
    # path('mostrar/', mostrar, name='insumo_list'),

]

user/urls.py
from django.urls import path
from user.views import *

app_name = 'user'

urlpatterns = [
    # user
    path('list/', UserListView.as_view(), name='user_list'),
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    # path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('change/password/', UserChangePasswordView.as_view(), name='user_change_password'),
]

proveedor/models.py
from django.db import models
from datetime import datetime
from django.forms import model_to_dict
# Create your models here.
from Sistema_Asomariec.models import BaseModel
from crum import get_current_user

class Provincia(models.Model):
    prvDescripcion = models.CharField(max_length=50, verbose_name='Descripcion')
    prvEstado = models.BooleanField(default=True, verbose_name='Estado')
    usuaReg = models.IntegerField(blank=True, null=True)
    usuaMod = models.IntegerField(blank=True, null=True)
    usuaEli = models.IntegerField(blank=True, null=True)
    prvFecReg = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    prvFecMod = models.DateTimeField(auto_now=True, blank=True, null=True)
    # prvFecEli = models.DateTimeField(default=datetime.now, blank=True, null=True)

    def __str__(self):
        return self.prvDescripcion

    def toJSON(self):
        item=model_to_dict(self)
        return item

    class Meta:
        verbose_name = 'Provincia'
        verbose_name_plural = 'Provincias'
        ordering = ['id']


class Proveedor(BaseModel):
    provincia = models.ForeignKey(Provincia, on_delete=models.PROTECT)
    proEmpresa = models.CharField(max_length=80, verbose_name='Empresa')
    proRuc= models.CharField(max_length=13, verbose_name='Ruc')
    proDireccion = models.CharField(max_length=80, verbose_name='Direccion')
    proDescripcion = models.CharField(max_length=200,null=True, verbose_name='Descripcion')
    proTelefono = models.CharField(max_length=25,blank=True, verbose_name='Telefono')
    proEmail = models.EmailField(max_length=80, verbose_name='Email')
    proEstado = models.BooleanField(default=True, verbose_name='Estado')

    def __str__(self):
        return self.proEmpresa

    def get_full_name(self):
        return '{} / {}'.format(self.proEmpresa, self.proRuc)

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        user = get_current_user()
        if user is not None:
            if not self.pk:
                self.user_creation = user
            else:
                self.user_updated = user
        super(Proveedor,self).save()

    def toJSON(self):
        item=model_to_dict(self)
        item['full_name']=self.get_full_name()
        item['provincia']= self.provincia.toJSON()
        return item

    class Meta:
        verbose_name = 'Proveedor'
        verbose_name_plural = 'Proveedores'
        ordering = ['id']

proveedor/forms.py
from django.forms import *


from proveedor.models import *

class ProveedorForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # for form in self.visible_fields():
        #     form.field.widget.attrs['class'] = 'form-control'
        #     form.field.widget.attrs['autocomplete'] = 'off'
        self.fields['proEmpresa'].widget.attrs['autofocus'] = True

    class Meta:
        model= Proveedor
        fields='__all__'
        # exclude=['catFecReg','catFecMod']
        widgets={
            'proEmpresa':TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Ingrese el Nombre'
                }
            ),
            'proRuc': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese el Ruc',
                    'minlength': '10'
                }
            ),
            'proDireccion': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese la Dirección'
                }
            ),
            'proTelefono': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese el N Telefónico',
                    'minlength': '10'
                }
            ),
            'proEmail': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese el Correo'
                }
            ),
            'provincia': Select(
                attrs={
                    'class': 'form-control mySelect2',
                    # 'placeholder': 'Ingrese el Correo'
                }
            ),
            'proDescripcion': TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese la Descripcion de la Empresa'
                }
            )
        }

        exclude=['user_creation','user_updated']
        # widgets = {
        #     'catDescripcion': TextInput(
        #         attrs={
        #             'placeholder': 'Ingrese un nombre',
        #         }
        #     ),
        #     # 'desc': Textarea(
        #     #     attrs={
        #     #         'placeholder': 'Ingrese un nombre',
        #     #         'rows': 3,
        #     #         'cols': 3
        #     #     }
        #     # ),
        # }

    # solo cuando voy a enviar con ajax
    def save(self, commit=True):
        data = {}
        form = super()
        try:
            if form.is_valid():
                form.save()
            else:
                data['error'] = form.errors
        except Exception as e:
            data['error'] = str(e)
        return data

proveedor/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, View
# Create your view here.
from proveedor.forms import ProveedorForm
from proveedor.models import *
from user.mixins import ValidatePermissionRequiredMixin


class ProveedorListarView(LoginRequiredMixin, ValidatePermissionRequiredMixin,ListView):
    model = Proveedor
    template_name = 'proveedor/proveedor/ListarProveedor.html'
    # permission_required = 'view_proveedor','delete_proveedor'
    permission_required = 'view_proveedor'
    # , 'delete_proveedor'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data={}
        try:
            action = request.POST['action']
            if action =='searchdata':
                # print('hola')
                data=[]
                for i in Proveedor.objects.filter(proEstado=1):
                    data.append(i.toJSON())
            # elif action=='eliminar':
            #     proveedor= Proveedor.objects.get(pk=request.POST['id'])
            #     proveedor.proEstado=False
            #     # proveedor.usuaEli=request.POST['usuaEli']
            #     proveedor.save()
            else:
                data['error']='Ha ocurrido un error'
        except Exception as e:
            data['error']= str(e)

        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['title'] = 'Listado de Clientes'
        context['create_url'] = reverse_lazy('proveedor:proveedor_crear')
        # context['list_url'] = reverse_lazy('erp:client_list')
        context['entity'] = 'Proveedor'
        return context

class ProveedorCrearView(LoginRequiredMixin, ValidatePermissionRequiredMixin,CreateView):
    model = Proveedor
    form_class =ProveedorForm
    template_name = 'proveedor/proveedor/FormProveedor.html'
    success_url = reverse_lazy('proveedor:proveedor_listar')
    permission_required = 'add_proveedor'

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self,request,*args,**kwargs):
        data=[]
        try:
            action=request.POST['action']
            if action == 'add':
                form=self.get_form()
                data=form.save()
            else:
                data['error']='No ha ingresado ninguna opcion'
        except Exception as e:
            data['error']=str(e)
        return JsonResponse(data)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_url'] = reverse_lazy('proveedor:proveedor_listar')
        context['action'] = 'add'
        return context

class ProveedorUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin,UpdateView):
    model = Proveedor
    form_class = ProveedorForm
    template_name = 'proveedor/proveedor/FormProveedor.html'
    success_url = reverse_lazy('proveedor:proveedor_listar')
    permission_required = 'change_proveedor'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                # print('hola')
                form = self.get_form()
                # form.cliFecMod = datetime.now()
                # form.cliEstado
                # print(form)
                # form("cli")
                # form.cliEstado=True
                # form['cliEstado']=True
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_url'] = reverse_lazy('proveedor:proveedor_listar')
        context['action'] = 'edit'
        return context


class ProveedorDelete(LoginRequiredMixin, ValidatePermissionRequiredMixin, View):
    # model = Cliente
    # template_name = 'cliente/ListarCliente.html'
    # success_url = reverse_lazy('cliente:cliente_listar')
    permission_required = 'delete_proveedor'
    # url_redirect = success_url


    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        # print(self.request)
        return super().dispatch(request, *args, **kwargs)

    # @permission_required('delete_cliente')
    def post(self, request, *args, **kwargs):
        data = {}

        try:
            action = request.POST['action']
            # print('eliminar')
            if action == 'eliminar':
                proveedor = Proveedor.objects.get(pk=request.POST['id'])
                proveedor.proEstado = False
                # proveedor.usuaEli=request.POST['usuaEli']
                proveedor.save()
                data['success']="Correcto"
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        # return HttpResponseRedirect(reverse_lazy('cliente:cliente_listar'))
        return JsonResponse(data)


class ProveedorDeleteView(LoginRequiredMixin, ValidatePermissionRequiredMixin,DeleteView):
    model = Proveedor
    template_name = 'proveedor/proveedor/DeleteProveedor.html'
    success_url = reverse_lazy('proveedor:proveedor_listar')
    permission_required = 'delete_proveedor'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        data={}
        try:
            action = request.POST['action']
            if action=='eliminar':
                proveedor= self.get_object()
                proveedor.proEstado=False
                proveedor.usuaEli=request.POST['usuaEli']
                proveedor.save()
            else:
                data['error']='No ha ingresado ninguna opcion'
        except Exception as e:
            data['error']=str(e)
        return JsonResponse(data)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['action'] = 'eliminar'
        context['list_url'] = reverse_lazy('proveedor:proveedor_listar')
        return context

templates/proveedor/proveedor/DeleteProveedor.html
{#{% extends 'base/body.html' %}#}
{% extends 'index.html' %}
{% load widget_tweaks %}
{% block content %}
    <form method="post" action="." enctype="multipart/form-data">

        <div class="card">
            <div class="card-body">
                <h1>Eliminar</h1>
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">

                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <span class="alert-icon"><i class="ni ni-like-2"></i></span>
                        <span class="alert-text"><strong>Danger!</strong> Ha ocurrido un error</span>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                {% endif %}
                {#                {{ form.cliEstado|remove_attr:'checked' }}#}

                <div class="alert alert-danger" role="alert">
                    <span class="alert-icon"><i class="fas fa-trash-alt"></i></span>
                    <span class="alert-text"><strong>Warning!</strong> Estas seguro que deseas eliminar a {{ object.proEmpresa }} </span>
                </div>
                <div class="col-6">
                    {#                    <h1>hola</h1>#}
                    {#                    {% ifequal action "eliminar" %}#}

                    {#                    {{ object.usuaReg }}#}
                    {#                    {{ object.usuaMod }}#}
                    {#                    {{ object.usuaEli|attr:'type:hidden'|attr:'value:1' }}#}
                    {#                    {% endifequal %}#}
                    <input type="hidden" name="usuaEli" value="1">


                </div>


                <button class="btn btn-info" type="submit">Aceptar</button>
                <a href="{{ list_url }}" class="btn btn-danger" role="button" aria-pressed="true">Cancelar</a>
            </div>


        </div>


    </form>


{% endblock %}

{% block javascript %}
    <script>
        {#    solo cuando envio con ajax#}
        $('form').on('submit', function (e) {
            e.preventDefault();
            {#console.log('hola');#}
            var parameters = new FormData(this);
            console.log(parameters);
            submit_with_ajax(window.location.pathname, 'Notification', '¿Estas seguro de realizar la siguiente acción?', parameters, function () {
                location.href = '{{ list_url }}';

            });


        });
        {#submit_with_aja();#}
        {#submit_with_ajax(window.location.pathname, 'Notification', '¿Estas seguro de realizar la siguiente acción?', paramet);#}


    </script>
{% endblock %}

templates/proveedor/proveedor/FormProveedor.html
{#{% extends 'base/body.html' %}#}
{% extends 'index.html' %}
{% load widget_tweaks %}
{% block content %}
    <form method="post" action="." enctype="multipart/form-data">

        <div class="card">
            <div class="card-body">
                <h1>Proveedor</h1>
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">

                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <span class="alert-icon"><i class="ni ni-like-2"></i></span>
                        <span class="alert-text"><strong>Danger!</strong> Ha ocurrido un error</span>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                {% endif %}


                {#                {% for field in form.visible_fields %}#}
                {#                    <div class="form-group">#}
                {#                        <label for="email">{{ field.label }}:</label>#}
                {#                        {{ field|add_class:'form-control'|attr:'autocomplete:off' }}#}
                {#                        {{ field }}#}
                {#                    </div>#}
                {#                {% endfor %}#}


                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="id_proEmpresa">Razon Social:</label>

                            {#                            {{ form.proEmpresa|add_class:"form-control" }}#}
                            {{ form.proEmpresa }}
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="id_proRuc">RUC:</label>

                            {#                            {{ form.proRuc|add_class:"form-control" }}#}
                            {{ form.proRuc }}
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="id_proDireccion">Direccion:</label>

                            {#                            {{ form.proDireccion|add_class:"form-control" }}#}
                            {{ form.proDireccion }}
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="id_proTelefono">Teléfono:</label>

                            {#                            {{ form.proTelefono|add_class:"form-control"|attr:'type:text' }}#}
                            {{ form.proTelefono }}
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="id_proEmail">Email:</label>

                            {#                            {{ form.proEmail|add_class:"form-control" }}#}
                            {{ form.proEmail }}
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="id_provincia">Provincia:</label>

                            {#                            {{ form.provincia|add_class:"form-control mySelect2" }}#}
                            {{ form.provincia }}

                            {#                            </select>#}
                        </div>

                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label for="id_proDescripcion">Descripcion:</label>

                            {#                            {{ form.provincia|add_class:"form-control mySelect2" }}#}
                            {{ form.proDescripcion }}

                            {#                            </select>#}
                        </div>

                    </div>


                    <div class="col-6">

                        {#                        {{ form.cliEstado|add_class:"custom-control-input"|attr:'checked' }}#}
                        {#                        <label>Hola</label>#}

                        {{ form.proEstado|attr:'checked'|attr:'type:hidden'|attr:'value:True' }}


                        {#                        <div class="custom-control custom-checkbox">#}
                        {#                            {{ form.cliEstado|add_class:"custom-control-input"|attr:'checked' }}#}
                        {#                            {{ form.cliEstado|add_class:"custom-control-input"|attr:'checked' }}#}
                        {#                            <label class="custom-control-label" for="id_cliEstado">Estado</label>#}
                        {#                        </div>#}


                    </div>

                    <div class="col-6">

                    </div>

                </div>
                <div class="text-right">
                    <button class="btn btn-primary" type="submit"> Guardar</button>
                    {#                <a type="button" class="btn btn-danger"role="button" aria-pressed="true">Cancelar</a>#}
                    <a href="{{ list_url }}" class="btn btn-danger" role="button" aria-pressed="true">Cancelar</a>
                    {#                <button class="btn btn-danger" type="submit"> </button>#}

                </div>
            </div>


        </div>


    </form>


{% endblock %}

{% block javascript %}
    <script>
        $(document).ready(function () {
            $('#id_proRuc').mask('0000000000000',{reverse: true});
            $('#id_proTelefono').mask('000000000000000000000000');

        });


    </script>

    <script>


        {% if form.errors %}
            var errors = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                errors += '{{ error }}\n';
            {% endfor %}
            Swal.fire({
                title: 'Error!',
                text: errors,
                icon: 'error'
            });
        {% endif %}
        {#    solo cuando envio con ajax#}
        $('form').on('submit', function (e) {
            e.preventDefault();
            {#console.log('hola');#}
            var parameters = new FormData(this);
            {#console.log(parameters);#}
            submit_with_ajax(window.location.pathname, 'Notification', '¿Estas seguro de realizar la siguiente acción?', parameters, function () {
                location.href = '{{ list_url }}';

            });

            {#console.log(parameters);#}

            /*
            $.ajax({
                url: window.location.pathname,
                type: 'POST',
                data: parameters,
                datatype: 'json',
                processData: false,
                contentType: false,
            }).done(function (data) {
                console.log(data);





            {#location.href = '{{ list_url }}'#}


            })
    */

        });
        {#submit_with_aja();#}
        {#submit_with_ajax(window.location.pathname, 'Notification', '¿Estas seguro de realizar la siguiente acción?', paramet);#}

        $('.mySelect2').select2({
            {#theme: 'bootstrap4',#}
            {#theme: "classic",#}
            dropdownAutoWidth: true,


            {#dropdownParent: $('#conte'),#}
            width: 'auto',
            {#languaje:'es',#}
            placeholder: 'Seleccione una opción',


            {#theme: 'bootstrap4',#}
        });
    </script>
{% endblock %}

templates/proveedor/proveedor/ListarProveedor.html
{% extends 'base/body.html' %}
{% load static %}
{% block head %}

<!-- Datatbles -->
    <link rel="stylesheet" href="{% static 'lib/assets/vendor/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'lib/assets/vendor/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'lib/assets/vendor/datatables.net-select-bs4/css/select.bootstrap4.min.css' %}">



{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h2 class="card-title p-0">Lista de Proveedores</h2>
            <div class="row">

                <div class="table-responsive py-4 ">
                    <table class="table table-flush align-items-center" id="table_id">
                        <thead class="thead-light">
                        <tr class="text-center">
                            <th>Id</th>
                            <th>Entidad</th>
                            <th>Ruc</th>
                            <th>Correo</th>
                            <th>Provincia</th>
                            <th>Accion</th>


                        </tr>
                        </thead>
{#                        <tfoot>#}
{#                        <tr>#}
{#                            <th>Id</th>#}
{#                            <th>Nombre</th>#}
{#                            <th>Apellido</th>#}
{#                            <th>Ruc</th>#}
{#                            <th>Telefono</th>#}
{#                            <th>Accion</th>#}
{##}
{#                        </tr>#}
{#                        </tfoot>#}
                        <tbody>
                        {#                        {% for object in object_list %}#}
                        {#                            <tr>#}
                        {#                                <td>{{ object.cliApellido }}</td>#}
                        {#                                <td>{{ object.cliApellido }}</td>#}
                        {#                                <td>{{ object.cliApellido }}</td>#}
                        {#                                <td>{{ object.catEstado }}</td>#}
                        {#                            </tr>#}
                        {##}
                        {#                        {% endfor %}#}

                        </tbody>
                    </table>
                </div>
            </div>
            <a href="{{ create_url }}" class="btn btn-primary btn-flat btnTest">
                <i class="fas fa-plus"></i> Nuevo registro
            </a>
            <a href="{{ list_url }}" class="btn btn-success btn-flat">
                <i class="fas fa-sync"></i> Actualizar
            </a>
        </div>
    </div>


{% endblock %}

{% block javascript %}
    <!-- Datatables -->
    <script src="{% static 'lib/assets/vendor/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-select/js/dataTables.select.min.js' %}"></script>
    {#funcion del datatable#}
    <script src="{% static 'js/proveedor/list.js' %}"></script>
    {#    <script>#}
    {#    $(function () {#}
    {#        $('#table_id').DataTable();#}
    {##}
    {#    });#}
    {#    </script>#}
{% endblock %}

templates/proveedor/proveedor/proveedorList.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
hola
</body>
</html>