Sistema_Asomariec/urls.py
"""Sistema_Asomariec URL Configuration

The `urlpatterns` list routes URLs to view. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function view
    1. Add an import:  from my_app import view
    2. Add a URL to urlpatterns:  path('', view.home, name='home')
Class-based view
    1. Add an import:  from other_app.view import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.shortcuts import render,HttpResponse
from django.urls import path, include

def mostrar(request):
    # return render(request, 'base/body.html')
    return render(request, 'test.html')
def mostrar2(request):
    # return render(request, 'base/body.html')
    return render(request, 'base/notificaciones.html')

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('hola/prueba/', mostrar2),
    path('admin/', admin.site.urls),
    path('hola/', mostrar),
    # path('hola/prueba/', mostrar2),
    path('prueba/', mostrar2),
    path('insumo/', include('insumo.urls')),
    path('cliente/', include('cliente.urls')),
    path('proveedor/', include('proveedor.urls')),
    path('compra/', include('compra.urls')),
    path('producto/', include('producto.urls')),
    path('venta/', include('venta.urls')),
    path('login/', include('login.urls')),
    path('reports/', include('reports.urls')),
    path('user/', include('user.urls')),
    path('seguridad/', include('seguridad.urls')),
    path('empresa/', include('empresa.urls')),


]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

producto/urls.py
from django.urls import path

from producto.views import *
from producto.view.vwproduccion import *

from producto.view.categoria.views import *

app_name = 'producto'

urlpatterns = [
    # insumo
    # path('producto/mostrar/', ProductoListView.as_view(), name='producto_mostrar'),
    # path('producto/create/', ProductoCreateView.as_view(), name='producto_create'),
    # path('producto/editar/<int:pk>/', ProductoUpdateView.as_view(), name='producto_edit'),
    # path('producto/eliminar/<int:pk>/', ProductoDeleteView.as_view(), name='producto_delete'),

    #     Categoria
    path('categoria/mostrar/', DetalleCategoriaView.as_view(), name='categoria_mostrar'),
    #     product
    path('product/mostrar/', ProductListView.as_view(), name='product_mostrar'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/editar/<int:pk>/', ProductUpdateView.as_view(), name='product_edit'),
    path('product/eliminar/', ProductoDelete.as_view(), name='product_delete'),
    # path('product/eliminar/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),

    #     produccion
    path('produccion/mostrar/', ProduccionListView.as_view(), name='produccion_mostrar'),
    path('produccion/create/', ProducionCreateView.as_view(), name='produccion_create'),
    # path('produccion/crear/<int:pk>/', ProducionCreateView.as_view(), name='produccion_create'),
    # path('produccion/eliminar/<int:pk>/', ProduccionDeleteView.as_view(), name='produccion_delete'),



]

user/urls.py
from django.urls import path
from user.views import *

app_name = 'user'

urlpatterns = [
    # user
    path('list/', UserListView.as_view(), name='user_list'),
    path('add/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    # path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    path('change/password/', UserChangePasswordView.as_view(), name='user_change_password'),
]

producto/models.py
from django.utils import timezone

from datetime import datetime

from crum import get_current_user

from Sistema_Asomariec.models import BaseModel
from Sistema_Asomariec.settings import MEDIA_URL, STATIC_URL
from django.db import models

from insumo.models import Insumo
# Create your models here.
from django.forms import model_to_dict

class Categoria(BaseModel):
    catDescripcion = models.CharField(max_length=100, verbose_name='CategoriaDescripcion')
    catEstado=models.BooleanField(default=True, verbose_name='Estado')


    def __str__(self):
        return self.catDescripcion

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        user = get_current_user()
        print(self.user_creation)
        if user is not None:
            if not self.pk:
                self.user_creation = user

            else:
                self.user_updated = user
                # self.date_updated=timezone.now()
        # self.modified_by = user
        super(Categoria,self).save()

    def toJSON(self):
        item= model_to_dict(self)
        return item
    class Meta:
        verbose_name='Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['id']


class Producto(BaseModel):
    prodDescripcion = models.CharField(max_length=100, verbose_name='Descripcion')
    categoria=models.ForeignKey(Categoria,on_delete=models.PROTECT)
    # prodFecElab=models.DateTimeField(default=datetime.now())
    prodImagen= models.ImageField(upload_to='producto', blank=True, null=True)
    prodImagen2= models.ImageField(upload_to='producto2', blank=True, null=True)
    # stock
    prodCantidad=models.IntegerField(default=0, blank=True, null=True)
    prodPrecio=models.DecimalField(default=0,max_digits=9, decimal_places=2)
    prodTotal=models.DecimalField(default=0.00,max_digits=9, decimal_places=2,blank=True, null=True)
    prodIva = models.DecimalField(default=0.12, max_digits=10, decimal_places=2)
    # prodTalla=models.CharField(max_length=100)
    prodCaracteristica=models.TextField(max_length=400, null=True, blank=True)
    # estado de la produccion
    # 1 finalizado; 2 en proceso
    prodEstprod=models.IntegerField(default=1,blank=True)
    # referencia si es por contrato o venta normal
    # 1 contrato, 2 normal
    prodTipo=models.IntegerField(default=2,blank=True)
    prodEstado = models.BooleanField(default=True, verbose_name='Estado')
    # usuaReg = models.IntegerField(blank=True, null=True)
    # usuaMod = models.IntegerField(blank=True, null=True)
    # usuaEli = models.IntegerField(blank=True, null=True)
    # prodFecReg = models.DateTimeField(default=datetime.now(), blank=True, null=True)
    # prodFecMod = models.DateTimeField(default=datetime.now(), blank=True, null=True)
    # prodFecEli = models.DateTimeField(default=datetime.now(), blank=True, null=True)

    def __str__(self):
        return self.prodDescripcion

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        user = get_current_user()
        print(self.user_creation)
        if user is not None:
            if not self.pk:
                self.user_creation = user

            else:
                self.user_updated = user
                # self.date_updated=timezone.now()
        # self.modified_by = user
        super(Producto,self).save()

    def toJSON(self):
        item=model_to_dict(self)
        item['prodImagen'] = self.get_image()
        item['prodImagen2'] = self.get_image2()
        item['categoria']=self.categoria.toJSON()
        item['prodPrecioTotal'] = format((self.prodPrecio*self.prodIva)+self.prodPrecio, '.2f')
        item['prodPrecio'] = format(self.prodPrecio, '.2f')
        item['prodIva'] = format(self.prodIva, '.2f')
        item['prodTotal'] = format(self.prodTotal, '.2f')
        # item['prodFecElab'] = self.prodFecElab.strftime('%Y-%m-%d')
        return item

    def get_image(self):
        if self.prodImagen:
            return '{}{}'.format(MEDIA_URL, self.prodImagen)
        return '{}{}'.format(STATIC_URL, 'img/empty.png')

    def get_image2(self):
        if self.prodImagen2:
            return '{}{}'.format(MEDIA_URL, self.prodImagen2)
        return '{}{}'.format(STATIC_URL, 'img/empty.png')

    class Meta:
        verbose_name='Producto'
        verbose_name_plural='Productos'
        ordering = ['id']


class Produccion(BaseModel):
    producto=models.ForeignKey(Producto,on_delete=models.PROTECT)
    prodcFecElab = models.DateTimeField(default=datetime.now())
    prodcCantidad = models.IntegerField(default=1)
    prodcTotal = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    prodcEstado = models.BooleanField(default=True, verbose_name='Estado')
    # estado de la produccion
    # prodcEstprod = models.IntegerField(default=0)
    # referencia si es por contrato o venta normal
    prodcTipo = models.IntegerField(default=1)

    def __str__(self):
        return self.producto.prodDescripcion

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        user = get_current_user()
        print(self.user_creation)
        if user is not None:
            if not self.pk:
                self.user_creation = user

            else:
                self.user_updated = user
                # self.date_updated=timezone.now()
        # self.modified_by = user
        super(Produccion,self).save()

    def toJSON(self):
        item=model_to_dict(self)
        item['producto'] = self.producto.toJSON()
        # item['prodcTotal'] = format((self.prodcTotal*self.prodIva)+self.prodPrecio, '.2f')
        item['prodcTotal'] = format(self.prodcTotal, '.2f')
        # item['prodIva'] = format(self.prodIva, '.2f')
        # item['prodTotal'] = format(self.prodTotal, '.2f')
        item['prodcFecElab'] = self.prodcFecElab.strftime('%Y-%m-%d')
        return item

    class Meta:
        verbose_name='Produccion'
        verbose_name_plural='Producciones'
        ordering = ['id']


class DetProducto(models.Model):
    # producto=models.ForeignKey(Producto,on_delete=models.PROTECT)
    produccion=models.ForeignKey(Produccion,on_delete=models.PROTECT)

    insumo=models.ForeignKey(Insumo,on_delete=models.PROTECT)
    # detcantidad= models.IntegerField(default=0)
    detprecio=models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    detCantidad = models.IntegerField(default=1)
    detSubtotal = models.DecimalField(default=0.0, max_digits=10, decimal_places=2)

    def __str__(self):
        return self.insumo.insDescripcion

    def toJSON(self):
        item= model_to_dict(self, exclude=['producto'])
        item['insumo']=self.insumo.toJSON()
        item['detprecio'] = format(self.detprecio, '.2f')
        item['detSubtotal'] = format(self.detSubtotal, '.2f')
        return item

    class Meta:
        verbose_name = 'Detalle de Producto'
        verbose_name_plural = 'Detalle de Productos'
        ordering = ['id']

class GastosAdicionales(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.PROTECT)
    gastdescripcion = models.CharField(max_length=100)
    gastprecio= models.DecimalField(default=0.00,max_digits=9, decimal_places=2)

    def __str__(self):
        return self.gastdescripcion

    def toJSON(self):
        item = model_to_dict(self, exclude=['producto'])
        item['gastprecio'] = format(self.gastprecio, '.2f')
        return item

    class Meta:
        verbose_name = 'Detalle Gastos Adicional'
        verbose_name_plural = 'Detalle Gastos Adicionales'
        ordering = ['id']

producto/view/categoria/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

from django.views.generic import TemplateView

from producto.models import Categoria
from producto.forms import CategoriaForm
from user.mixins import ValidatePermissionRequiredMixin


class DetalleCategoriaView(LoginRequiredMixin, ValidatePermissionRequiredMixin,TemplateView):
    template_name = 'producto/categoria/FormCategoria.html'
    permission_required = 'view_categoria','delete_categoria','change_categoria','add_categoria'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data={}
        try:
            action = request.POST['action']
            if action== 'add':
                # print('Proband')
                categoria= Categoria()
                categoria.catDescripcion=request.POST['catDescripcion']
                categoria.save()
            elif action=='searchdata':
                data=[]
                for i in Categoria.objects.filter(catEstado=1):
                # for i in Categoria.objects.all():
                    # print(i.toJSON)
                    data.append(i.toJSON())
                # print('ggg')
                # print(data)
            elif action=='edit':
                categoria= Categoria.objects.get(pk=request.POST['id'])
                categoria.catDescripcion=request.POST['catDescripcion']
                categoria.save()
            elif action=='delete':
                categoria=Categoria.objects.get(pk=request.POST['id'])
                categoria.catEstado=0
                categoria.save()
            else:
                data['error']='Ha ocurrido un error'
        except Exception as e:
            data['error']=str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CategoriaForm()
        context['action'] = 'add'
        return context

# class CategoriaListView(ListView):
#     model = Categoria
#     template_name = 'producto/categoria/ShowCategoria.html'
#
#     @method_decorator(csrf_exempt)
#     def dispatch(self, request, *args, **kwargs):
#         return super().dispatch(request, *args, **kwargs)
#
#     def post(self, request, *args, **kwargs):
#         data = {}
#         try:
#             action = request.POST['action']
#             if action == 'searchdata':
#                 data = []
#                 for i in Categoria.objects.all():
#                     data.append(i.toJSON())
#             else:
#                 data['error'] = 'Ha ocurrido un error'
#         except Exception as e:
#             data['error'] = str(e)
#         return JsonResponse(data, safe=False)
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['create_url'] = reverse_lazy('producto:categoria_mostrar')
#         context['list_url'] = reverse_lazy('producto:categoria_mostrar')
#         return context
#
# class CategoriaCreateView(CreateView):
#     model = Categoria
#     template_name = 'producto/categoria/FormCategoria.html'
#     success_url = reverse_lazy('producto:categoria_mostrar')
#     # url_redirect=success_url
#
#     def dispatch(self, request, *args, **kwargs):
#         return super().dispatch(request, *args, **kwargs)
#
#     def post(self, request, *args, **kwargs):
#         data = {}
#         try:
#             action = request.POST['action']
#             if action == 'add':
#                 form = self.get_form()
#                 data = form.save()
#             else:
#                 data['error'] = 'No ha ingresado a ninguna opción'
#         except Exception as e:
#             data['error'] = str(e)
#         return JsonResponse(data)
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         # context['title'] = 'Creación un Cliente'
#         # context['entity'] = 'Clientes'
#         context['list_url'] = self.success_url
#         context['action'] = 'add'
#         return context

templates/producto/categoria/DeleteCatagoria.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/producto/categoria/FormCategoria.html
{% extends 'base/body.html' %}

{% load static %}
{% block head %}

    {#    <script src="{% static 'lib/plugins/jquery/jquery.min.js' %}"></script>#}
    {#    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">#}
    {#    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/dataTables.bootstrap4.min.css">#}
    {##}
    {#    <script type="text/javascript" charset="utf8"#}
    {#            src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>#}
    {#    <script src="https://cdn.datatables.net/1.10.21/js/dataTables.bootstrap4.min.js"></script>#}
    <!-- Datatables -->
    <link rel="stylesheet" href="{% static 'lib/assets/vendor/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'lib/assets/vendor/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'lib/assets/vendor/datatables.net-select-bs4/css/select.bootstrap4.min.css' %}">



{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h2 class="card-title p-0">Categoria de Productos</h2>
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush" id="table_idcat">
                            <thead class="thead-light text-center">
                            <tr>
                                <th scope="col">N</th>
                                <th scope="col">Nombre</th>
                                <th scope="col">Accion</th>

                            </tr>
                            </thead>
                            <tbody class="text-center">


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <a href="#" class="btn btn-primary btn-flat btnAddcat">
                <i class="fas fa-plus"></i> Nuevo registro
            </a>

        </div>
    </div>


{% endblock %}

{% block javascript %}



    <!-- Modal -->


    <script src="{% static 'lib/assets/vendor/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-select/js/dataTables.select.min.js' %}"></script>
    {#funcion del datatable#}
    {#    categoria#}
    <script src="{% static 'js/producto/categoria/list.js' %}"></script>





    <div class="modal fade" id="myModalCategoria" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <form method="post" action="." enctype="multipart/form-data" id="form_IDcat">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Categoria</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="container-fluid">
                            <input name="action" type="hidden" value="addcat">
                            <input name="user1" id="user1" type="hidden" value="1">
                            <input name="id" id="id" type="hidden" value="0">
                            <div class="form-group">
                                <label for="id_catDescripcion">Nombre:</label>

                                {{ form.catDescripcion }}
                                {#                                {{ form.catFecReg }}#}
                                {#                                {{ form.catFecMod }}#}
                            </div>

                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                </div>
            </div>
        </form>

    </div>
{% endblock %}

templates/producto/categoria/ShowCategoria.html
{% extends 'base/body.html' %}
{% load static %}
{% block head %}


    <link rel="stylesheet" href="{% static 'lib/assets/vendor/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'lib/assets/vendor/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'lib/assets/vendor/datatables.net-select-bs4/css/select.bootstrap4.min.css' %}">



{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h2 class="card-title p-0">Lista de Categoria de Productos</h2>
            <div class="row">

                <div class="table-responsive py-4 ">
                    <table class="table table-flush align-items-center" id="table_id">
                        <thead class="thead-light">
                        <tr>
                            <th>Id</th>
                            <th>Nombre</th>
                            <th>Accion</th>
                        </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>
            <a href="{{ create_url }}" class="btn btn-primary btn-flat btnTest">
                <i class="fas fa-plus"></i> Nuevo registro
            </a>
            <a href="{{ list_url }}" class="btn btn-success btn-flat">
                <i class="fas fa-sync"></i> Actualizar
            </a>
        </div>
    </div>


{% endblock %}

{% block javascript %}
    <script src="{% static 'lib/assets/vendor/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'lib/assets/vendor/datatables.net-select/js/dataTables.select.min.js' %}"></script>
    {#funcion del datatable#}
    <script src="{% static 'js/producto/categoria/list.js' %}"></script>


{% endblock %}